"""Pack the BonziBUDDY frames the simulation uses into one sprite atlas.

Usage:
    python scripts/build-bonzi-atlas.py "<path to the BonziBUDDY Characters zip>"

The zip is the 1,252-frame Microsoft Agent dump (Images/0001.png ... 1252.png,
200x160 each) whose background is the MS Agent transparency key, pure cyan.
This keys the cyan out, packs only the frames listed below into
public/bonzi/bonzi-atlas.webp (lossless, each cell framed by a transparent gutter
so scaled rendering at 125%/150% display zoom never bleeds a neighbor frame in),
and regenerates src/data/bonziAtlas.ts with the cell order and a content hash
(used to cache-bust the image, so a new layout never meets a stale atlas). The
animations themselves live in src/data/bonziSprites.ts; a unit test checks every
frame they use is in the atlas.

Requires Pillow and numpy.
"""

import hashlib
import sys
import zipfile
from io import BytesIO
from pathlib import Path

import numpy as np
from PIL import Image

CELL_W, CELL_H = 200, 160
PAD = 1  # transparent gutter on every side of each cell
COLS = 10

# (from, to) inclusive frame ranges to pack, by original frame number.
RANGES = [
    (1, 7),  # rest pose + its six lip-sync mouth overlays
    (26, 27),  # half and full blink overlays for the rest pose
    (29, 39),  # "explain" gesture (arms open) + its six mouth overlays
    (41, 42),  # explain back to rest
    (346, 364),  # wave
    (1141, 1160),  # show: drops in on a vine
    (1168, 1188),  # hide: swings away on a vine
]

ROOT = Path(__file__).resolve().parent.parent
ATLAS = ROOT / 'public' / 'bonzi' / 'bonzi-atlas.webp'
MANIFEST = ROOT / 'src' / 'data' / 'bonziAtlas.ts'


def frames() -> list[int]:
    return sorted({n for lo, hi in RANGES for n in range(lo, hi + 1)})


def keyed(data: bytes) -> Image.Image:
    img = np.array(Image.open(BytesIO(data)).convert('RGBA'))
    cyan = (img[:, :, 0] == 0) & (img[:, :, 1] == 255) & (img[:, :, 2] == 255)
    img[cyan] = (0, 0, 0, 0)
    return Image.fromarray(img)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    wanted = frames()
    rows = (len(wanted) + COLS - 1) // COLS
    pitch_w, pitch_h = CELL_W + 2 * PAD, CELL_H + 2 * PAD
    atlas = Image.new('RGBA', (COLS * pitch_w, rows * pitch_h), (0, 0, 0, 0))
    with zipfile.ZipFile(sys.argv[1]) as archive:
        for index, frame in enumerate(wanted):
            cell = keyed(archive.read(f'Images/{frame:04d}.png'))
            if cell.size != (CELL_W, CELL_H):
                sys.exit(f'frame {frame} is {cell.size}, expected {(CELL_W, CELL_H)}')
            atlas.paste(cell, ((index % COLS) * pitch_w + PAD, (index // COLS) * pitch_h + PAD))

    ATLAS.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(ATLAS, 'WEBP', lossless=True, method=6)
    version = hashlib.sha1(ATLAS.read_bytes()).hexdigest()[:10]
    MANIFEST.write_text(
        '// Generated by scripts/build-bonzi-atlas.py. Do not edit by hand.\n'
        f'// Cell layout of public/bonzi/bonzi-atlas.webp: one {CELL_W}x{CELL_H} frame per cell,\n'
        '// row-major in the order of `frames` (original BonziBUDDY frame numbers), each\n'
        '// framed by a `pad`-pixel transparent gutter. `version` hashes the image.\n'
        'export const BONZI_ATLAS = {\n'
        "  file: 'bonzi/bonzi-atlas.webp',\n"
        f"  version: '{version}',\n"
        f'  cellW: {CELL_W},\n'
        f'  cellH: {CELL_H},\n'
        f'  pad: {PAD},\n'
        f'  cols: {COLS},\n'
        f'  frames: [{", ".join(map(str, wanted))}],\n'
        '} as const\n',
        encoding='utf-8',
    )
    print(f'{len(wanted)} frames -> {ATLAS.relative_to(ROOT)} ({ATLAS.stat().st_size // 1024} KB)')


if __name__ == '__main__':
    main()
