"""Build Bonzi's recorded voice for the simulation.

Usage:
    python scripts/build-bonzi-voice.py

Bonzi's lines come from src/data/bonziBrain.ts (bonziVoiceLines(), read through
Node). Each line was recorded on samtts.com's BonziBUDDY Voice page (SAPI4 "Adult
Male #2, American English (TruVoice)", pitch 50, speed 150) and saved as
assets-src/bonzi-voice/<id>.wav, where <id> is the first 10 hex digits of the
SHA-1 of the text that was spoken. The masters stay out of git (see .gitignore).

For every line with a recording this trims the silence at both ends, encodes a
small mono MP3 into public/bonzi/voice/ (named by a hash of its bytes, so a
browser never keeps a stale copy), and measures its loudness every 50 ms (0
silent to 3 loud) to drive the lip-sync. It then regenerates
src/data/bonziVoice.ts and lists the lines that still need recording. Lines
without a clip fall back to the browser's synthetic voice.

Requires ffmpeg on PATH, Node, and numpy.
"""

import hashlib
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
MASTERS = ROOT / 'assets-src' / 'bonzi-voice'
OUT_DIR = ROOT / 'public' / 'bonzi' / 'voice'
MANIFEST = ROOT / 'src' / 'data' / 'bonziVoice.ts'

RATE = 11025  # SAPI4 TruVoice speaks at 11,025 Hz mono
BITRATE = '32k'
STEP_MS = 50
LEVELS = [0.12, 0.35, 0.65]  # loudness (relative to the clip's peak) where levels 1, 2, 3 start
# Keep a breath of silence at each end and drop the rest. The recordings end in a
# flat hiss around -46 dB; speech never gets that quiet, so the cut sits above it.
TRIM = (
    'silenceremove=start_periods=1:start_threshold=-42dB:start_silence=0.03,'
    'areverse,silenceremove=start_periods=1:start_threshold=-42dB:start_silence=0.08,areverse'
)


def voice_lines() -> list[dict]:
    script = (
        "const { bonziVoiceLines } = await import('./src/data/bonziBrain.ts');"
        'console.log(JSON.stringify(bonziVoiceLines()))'
    )
    result = subprocess.run(
        ['node', '--input-type=module', '-e', script], cwd=ROOT, check=True, capture_output=True, text=True
    )
    return json.loads(result.stdout)


def clip_id(say: str) -> str:
    return hashlib.sha1(say.encode('utf-8')).hexdigest()[:10]


def ffmpeg(*args: str) -> bytes:
    return subprocess.run(['ffmpeg', '-v', 'error', '-y', *args], check=True, capture_output=True).stdout


def encode(wav: Path) -> bytes:
    # A real file, not a pipe: the MP3 muxer seeks back to write the header that
    # tells browsers how much encoder padding to skip.
    scratch = OUT_DIR / '.encoding.mp3'
    ffmpeg('-i', str(wav), '-af', TRIM, '-ac', '1', '-ar', str(RATE), '-codec:a', 'libmp3lame', '-b:a', BITRATE, str(scratch))
    data = scratch.read_bytes()
    scratch.unlink()
    return data


def envelope(wav: Path) -> str:
    raw = ffmpeg('-i', str(wav), '-af', TRIM, '-f', 's16le', '-ac', '1', '-ar', str(RATE), '-')
    pcm = np.frombuffer(raw, dtype='<i2').astype(np.float64)
    step = RATE * STEP_MS // 1000
    windows = [pcm[start : start + step] for start in range(0, len(pcm), step)]
    rms = np.array([np.sqrt(np.mean(window**2)) for window in windows if len(window)])
    peak = float(np.percentile(rms, 95)) if len(rms) else 0.0
    if peak <= 0:
        return '0' * len(rms)
    return ''.join(str(level) for level in np.digitize(rms / peak, LEVELS))


def main() -> None:
    if len(sys.argv) != 1:
        sys.exit(__doc__)
    lines = voice_lines()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    clips: dict[str, dict[str, str]] = {}
    missing: list[str] = []
    for number, line in enumerate(lines, 1):
        wav = MASTERS / f"{clip_id(line['say'])}.wav"
        if not wav.exists():
            missing.append(f"{number:02d}  {line['say']}")
            continue
        data = encode(wav)
        name = hashlib.sha1(data).hexdigest()[:10] + '.mp3'
        (OUT_DIR / name).write_bytes(data)
        clips[line['text']] = {'file': name, 'env': envelope(wav)}

    # This folder holds only what this script builds: drop clips no line uses.
    for old in OUT_DIR.glob('*.mp3'):
        if old.name not in {clip['file'] for clip in clips.values()}:
            old.unlink()

    entries = '\n'.join(
        f"    {json.dumps(text)}: {{ file: '{clip['file']}', env: '{clip['env']}' }},"
        for text, clip in clips.items()
    )
    MANIFEST.write_text(
        '// Generated by scripts/build-bonzi-voice.py. Do not edit by hand.\n'
        "// Bonzi's recorded voice: one MP3 per line in public/bonzi/voice/, keyed by the\n"
        '// exact line text. `env` is the clip loudness, one digit (0 silent to 3 loud)\n'
        '// per `stepMs`, which drives the lip-sync.\n'
        'export type BonziClip = { file: string; env: string }\n'
        '\n'
        'export const BONZI_VOICE: { dir: string; stepMs: number; clips: Readonly<Record<string, BonziClip>> } = {\n'
        "  dir: 'bonzi/voice',\n"
        f'  stepMs: {STEP_MS},\n'
        '  clips: {\n'
        + (entries + '\n' if entries else '')
        + '  },\n'
        '}\n',
        encoding='utf-8',
    )
    size = sum(path.stat().st_size for path in OUT_DIR.glob('*.mp3'))
    print(f'{len(clips)} of {len(lines)} lines voiced -> {OUT_DIR.relative_to(ROOT)} ({size // 1024} KB)')
    if missing:
        print(f'{len(missing)} still to record:')
        print('\n'.join(missing))


if __name__ == '__main__':
    main()
