// Generated by scripts/build-bonzi-atlas.py. Do not edit by hand.
// Cell layout of public/bonzi/bonzi-atlas.webp: one 200x160 frame per cell,
// row-major in the order of `frames` (original BonziBUDDY frame numbers), each
// framed by a `pad`-pixel transparent gutter. `version` hashes the image.
export const BONZI_ATLAS = {
  file: 'bonzi/bonzi-atlas.webp',
  version: 'bf2b694d20',
  cellW: 200,
  cellH: 160,
  pad: 1,
  cols: 10,
  frames: [1, 2, 3, 4, 5, 6, 7, 26, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188],
} as const
